fastboot flash partition ./gpt_both0.bin
fastboot flash aboot ./emmc_appsboot-test-signed.mbn
fastboot flash hyp ./qcom_partitions/hyp.mbn
fastboot flash rpm ./qcom_partitions/rpm.mbn
fastboot flash sbl1 ./qcom_partitions/sbl1.mbn
fastboot flash tz ./qcom_partitions/tz.mbn
fastboot flash cdt ./qcom_partitions/sbc_1.0_8016.bin
fastboot flash fsc ./stock_partitions/fsc.bin
fastboot flash fsg ./stock_partitions/fsg.bin
fastboot flash modem ./stock_partitions/modem.bin
fastboot flash modemst1 ./stock_partitions/modemst1.bin
fastboot flash modemst2 ./stock_partitions/modemst2.bin
